[package]
name = "cpu-arl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"
sysinfo = "0.33.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["time", "rt", "macros"] }

[features]
cgroup = []
